Learning Numpy 

In [ ]:
import practice as np

In [1]:
print("hello print ")

hello print 


In [ ]:
import practice as np 

array = np.array([[1,2,3,4,5,6],[2,3,4,4,5,6],[1,2,3,4,5,6]])
print(array)

[[1 2 3 4 5 6]
 [2 3 4 4 5 6]
 [1 2 3 4 5 6]]


In [ ]:
import practice as np
array1 = np.array([[1,2,3,4,5,6],[2,3,4,4,5,6],[1,2,3,4,5,6]])
print(array1)

[[1 2 3 4 5 6]
 [2 3 4 4 5 6]
 [1 2 3 4 5 6]]


In [3]:
print ( array1*2)

[[ 2  4  6  8 10 12]
 [ 4  6  8  8 10 12]
 [ 2  4  6  8 10 12]]


### List vs Numpy array

In [17]:


array4 = np.arange(1000000000)

print(array4)

[        0         1         2 ... 999999997 999999998 999999999]


In [16]:
list=[i*i for i in range(1000000000)]
print (list)

MemoryError: 

In [ ]:
import time
import practice as np
start=time.time()
list = [i*i for i in range(100000)]
print("List time ", time.time()-start)
start=time.time()
Array= np.array(100000)
print("\nArray time ",time.time()-start)

List time  0.017278432846069336

Array time  0.00017404556274414062


# Numpy Functions


In [13]:
zeros_array=np.zeros((4,4))
print("zeros array :", zeros_array)

ones_array=np.ones((3,3))
print("\nOnes array :", ones_array)

full_array=np.full((3,3),7)
print("\nFull Array :",full_array)

random_array=np.random.random((3,3))
print("\nRandom array",random_array)

sequence_array=np.arange(0,11,2)
print("\nSquence Array:",sequence_array)

zeros array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full Array : [[7 7 7]
 [7 7 7]
 [7 7 7]]

Random array [[0.93448903 0.00859574 0.42879818]
 [0.915606   0.81347602 0.39149642]
 [0.37736341 0.27954452 0.64075365]]

Squence Array: [ 0  2  4  6  8 10]


# Vector, Matrices and Tesnor

In [18]:
vector=np.array([1,2,3])
print("Vector= ",vector)

matrices=np.array([[1,2,3],[4,5,6]])
print("Matrices= ",matrices)

tensor=np.array([[[1,2,3],[1,2,3]],
                 [[1,2,3],[1,2,3]]])
print("Tensor= ",tensor)
print(tensor.shape)


Vector=  [1 2 3]
Matrices=  [[1 2 3]
 [4 5 6]]
Tensor=  [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
(2, 2, 3)


In [ ]:
import practice as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)


Shape  (2, 3)
Dimension  2
Size  6
DType  int64


In [ ]:
import practice as np
arr=np.arange((12))
print("array ", arr)


reshaped=arr.reshape((3,4))
print("Reshape array",reshaped)

flat=reshaped.flatten()
print("Flatend ",flat)

transpose=reshaped.T
print ("The transpose of reshapes matrice is ", transpose)

array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatend  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Thr transpose of reshapes matrice is  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
