Learning Numpy 

In [1]:
print("hello print ")

hello print 


In [ ]:
import numpy as np 

array = np.array([[1,2,3,4,5,6],[2,3,4,4,5,6],[1,2,3,4,5,6]])
print(array)

[[1 2 3 4 5 6]
 [2 3 4 4 5 6]
 [1 2 3 4 5 6]]


In [2]:
import numpy as np
array1 = np.array([[1,2,3,4,5,6],[2,3,4,4,5,6],[1,2,3,4,5,6]])
print(array1)

[[1 2 3 4 5 6]
 [2 3 4 4 5 6]
 [1 2 3 4 5 6]]


In [3]:
print ( array1*2)

[[ 2  4  6  8 10 12]
 [ 4  6  8  8 10 12]
 [ 2  4  6  8 10 12]]


### List vs Numpy array

In [17]:


array4 = np.arange(1000000000)

print(array4)

[        0         1         2 ... 999999997 999999998 999999999]


In [16]:
list=[i*i for i in range(1000000000)]
print (list)

MemoryError: 

In [2]:
import time
import numpy as np
start=time.time()
list = [i*i for i in range(100000)]
print("List time ", time.time()-start)
start=time.time()
Array= np.array(100000)
print("\nArray time ",time.time()-start)

List time  0.017278432846069336

Array time  0.00017404556274414062


# Numpy Functions


In [12]:
zeros_array=np.zeros((4,4))
print("zeros array :", zeros_array)

ones_array=np.ones((3,3))
print("\nOnes array :", ones_array)

full_array=np.full((3,3),7)
print("Full Array :",full_array)

random_array=np.random.random((3,3))
print("Random array",random_array)

sequence_array=np.arange(0,11,2)
print("Squence Array:",sequence_array)

zeros array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full Array : [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random array [[0.59643197 0.7319712  0.36536349]
 [0.30043469 0.43587592 0.36080592]
 [0.39872699 0.11326632 0.63066221]]
Squence Array: [ 0  2  4  6  8 10]
