## Numpy Array Operation


In [4]:
import numpy as np

In [16]:
unsorted = [3,4,5,1,2,8,9,7,9,5]
sorted=np.sort(unsorted)
print("Sorted ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=1))

Sorted  [1 2 3 4 5 5 7 8 9 9]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


## Filtering & Masking 


In [31]:
numbers = np.array([1,2,3,4,5,6,7,8,9,0,11,12,13,14,15,16,17,18,19,20,21])
even_numbers=numbers[numbers>5]
print(even_numbers)
print("Even Numbers ",numbers[numbers>5])


number=np.array([1,2,3,4,5,6,7,8,9,10,11])
condition = np.where((number>5) & (number<9),number*2,number*0)
print(condition)

[ 6  7  8  9 11 12 13 14 15 16 17 18 19 20 21]
Even Numbers  [ 6  7  8  9 11 12 13 14 15 16 17 18 19 20 21]
[ 0  0  0  0  0 12 14 16  0  0  0]


## Adding & Removing

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)
print(arr1 + arr2)


a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

[1 2 3 4 5 6]
[5 7 9]
Compatibility shapes False


# Adding Verticaly & Horizontaly 


In [44]:
original=np.array([[1,2,3],[4,5,6]])
new_row=np.array([[7,8,9],[11,22,33]])
print(np.vstack((original,new_row)))

new_col=np.array([[45],[90]])
print(np.hstack((original,new_col)))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]]
[[ 1  2  3 45]
 [ 4  5  6 90]]


## Delete Function


In [46]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
deleted=np.delete(arr,4)
print(deleted)
print(np.delete(arr,2))

[1 2 3 4 6 7 8 9 0]
[1 2 4 5 6 7 8 9 0]
