Learning Numpy 

In [1]:
print("hello print ")

hello print 


In [8]:
import numpy as np 

array = np.array([[1,2,3,4,5,6],[2,3,4,4,5,6],[1,2,3,4,5,6]])
print(array)

[[1 2 3 4 5 6]
 [2 3 4 4 5 6]
 [1 2 3 4 5 6]]
