Learning Numpy 

In [1]:
print("hello print ")

hello print 


In [ ]:
import numpy as np 

array = np.array([[1,2,3,4,5,6],[2,3,4,4,5,6],[1,2,3,4,5,6]])
print(array)

[[1 2 3 4 5 6]
 [2 3 4 4 5 6]
 [1 2 3 4 5 6]]


In [2]:
import numpy as np
array1 = np.array([[1,2,3,4,5,6],[2,3,4,4,5,6],[1,2,3,4,5,6]])
print(array1)

[[1 2 3 4 5 6]
 [2 3 4 4 5 6]
 [1 2 3 4 5 6]]


In [3]:
print ( array1*2)

[[ 2  4  6  8 10 12]
 [ 4  6  8  8 10 12]
 [ 2  4  6  8 10 12]]


List vs Numpy array

In [17]:


array4 = np.arange(1000000000)

print(array4)

[        0         1         2 ... 999999997 999999998 999999999]


In [16]:
list=[i*i for i in range(1000000000)]
print (list)

MemoryError: 